### ISSUE TITLE
Importing .tox profile from qTox

### ISSUE THREAD

**Issue by Jomiph** [Antidote-for-Tox/Antidote#160] opened 2015-09-22 13:34 UTC
I tried to import my .tox file from qTox, via dropbox as suggested in the app. This made the app crash on launch every time. Reinstalled the app, same thing. It opens the app, asks if you want to use the profile, than asks for a profile name. When I click ok, app instantly crashes. Running ios9.

**Comment by Jomiph** [comment] 2015-09-22 13:38
Did another attempt, but first I deleted the password in qTox. That way it imported perfectly into Antidote. Maybe add that to the instructions :)

**Comment by dvor** [comment] 2015-09-22 14:11
Duplicate of https://github.com/Antidote-for-Tox/Antidote/issues/148

**Comment by dvor** [comment] 2015-09-22 14:12
Hey @Jomiph, thanks for reporting

This crash is fixed as part of [Startup Flow](https://github.com/Antidote-for-Tox/Antidote/milestones/Startup%20flow) milestone. It is almost ready, I really hope that I'll submit new build to TestFlight today.

**Closed by dvor** 2015-09-22 14:12 UTC
Labels: duplicate

**Comment by Jomiph** [comment] 2015-09-22 15:14
Sorry about the dupe, didn't realize at first it was a crypto issue. Looking forward to the new milestone :)
