### ISSUE TITLE
Chat bar closes prematurely

### ISSUE THREAD

**Issue by Sorunome** [Antidote-for-Tox/Antidote#238] opened 2016-09-30 10:17 UTC
If you have they keyboard closed you can get the chat bar to vanish quite easily:
you know how you can swipe from the left to get to the chat view instrad of hitting "<chats"? Do that but not all the way and swipe it back, now instead of the message bar you have the contacts/chats/settings/profile buttons

**Comment by dvor** [comment] 2016-09-30 10:27
Duplicate of #221

**Closed by dvor** 2016-09-30 10:27 UTC
Labels: duplicate
